### PR TITLE
Added some addons to the index

### PR DESCRIPTION
**Pull request by BlueTree242**

### CODE REVIEW

**Comment by BlueTree242** [comment]
you are right, all addons are small, but then there would be no addon if we remove small addons... Only staffchat would remain.. Also staffchat can work alone so i personally don't consider it an addon. Feel free to correct if im wrong :)

**Comment by GreemDev** [comment]
You're not going to get this PR merged by trying to redefine addon. And also, DiscordSRV Staff Chat can't run on its own. It is an addon. It adds on functionality.

**Comment by BlueTree242** [comment]
I never tried to redefine the meaning... Anyways i don't really care about it getting merged.. Its just a PR with a few lines to docs

**Comment by BlueTree242** [comment]
Give me 1 minute

**Comment by BlueTree242** [comment]
https://github.com/DiscordSRV/Staff-Chat/blob/master/src/main/java/com/rezzedup/discordsrv/staffchat/StaffChatPlugin.java#L124

**Comment by Dinty1** [comment]
> I never heard the word "Addon" defines same developers...

It doesn't on its own, but if we list "addons" on our wiki then there will be the expectation that they are managed by us.

> you are right, all addons are small, but then there would be no addon if we remove small addons... Only staffchat would remain.. Also staffchat can work alone so i personally don't consider it an addon. Feel free to correct if im wrong :)

- If we add small and unknown plugins to our list then it will only clutter it up. We would rather have a small list of reliable and well known plugins.
- StaffChat does work on its own, however it is intended to be used with DiscordSRV. This will be the same for the alerts module when it is released as a standalone project.

**Comment by BlueTree242** [comment]
Ok, do i remove all except interactive chat? This one is known

**Comment by BlueTree242** [comment]
I can get them all? Or there is an exception to the ones developed by you?

**Comment by BlueTree242** [comment]
Alright 👍 (but btw you forgot about the note granny left about if someone wants his addon on list)

**Pull request merged**
