### PR TITLE
Add plugins to "Plugins that use our API"

### LINKED ISSUE #51: Plugins that use API
https://modrinth.com/plugin/slashadditions
https://www.spigotmc.org/resources/custom-bans-plus-fully-customizable-ban-manager.89075/

### LINKED ISSUE #54: Plugin list request for using API
Request for NeoPerformance, https://www.spigotmc.org/resources/neoperformance.103183/, to be listed as plugin using discordsrv api

### PR DESCRIPTION
**Pull request by PadowYT2**
## Additions
- #51
- [DiscordSRVOAuth](https://hangar.papermc.io/PadowYT2/DiscordSRVOAuth/)

---

*for github*
Closes #51
Closes #54 (due to being unmaintained/unpublished)

### CODE REVIEW

**Review by Dinty1 — APPROVED** [review]
LGTM

**Comment by thewilloftheshadow** [comment]
Minor nit but when you make a PR that overrules another PR you'd put `Supersedes #64`
PR itself lgtm tho

**Comment by PadowYT2** [comment]
> Minor nit but when you make a PR that overrules another PR you'd put `Supersedes #64`

Never heard of this, but looks like to not work...?

**Review by granny — APPROVED** [review]
Thank you for the PR!

**Pull request merged**
