### PR TITLE
Add account linking via text channels to the config list

### PR DESCRIPTION
**Pull request by thewilloftheshadow**

### CODE REVIEW

**Review by granny — APPROVED** [review]

**Comment by Karfyy** [comment]
Hi, I want to ask if he is going to discordsrv do so that I don't have to send a code to the pm bot but to the discord channel?

**Comment by granny** [comment]
@Karfyy Already a built-in feature. Just specify a `link` channel pair in the `Channels` option of your `config.yml`.

You can also disable the DM linking by setting `MinecraftDiscordAccountLinkedUsePM` to false.

If you need help setting any of this up then feel free to create a support ticket in our discord server: https://discordsrv.com/discord

**Comment by Karfyy** [comment]
Where can I find it more precisely?

**Comment by granny** [comment]
Read all of what I said again. I already mentioned where to find it and what to do if you need help.

**Comment by granny** [comment]
> Read all of what I said again. **I already mentioned where to find it and what to do if you need help.**

> If you need help setting any of this up then feel free to create a support ticket in our discord server: https://discordsrv.com/discord

**Pull request merged**
